language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1

gemfile:
  - Gemfile

sudo: false

cache: bundler

before_install: "rm ${BUNDLE_GEMFILE}.lock"

before_script: "bundle update"

script: "bundle exec rake test"
